lifeful:
  security:
    jwt:
      secret-key: ${JWT_KEY:4837e9ab8772c5db4e07758a35b14955}
      expiration-time: 12h

spring:
  application:
    name: lifeful-api

  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 100

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: redis
      port: 6379

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, caches, openapi, metrics
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 15s
  metrics:
    tags:
      application: ${spring.application.name}
