lifeful:
  security:
    jwt:
      secret-key: ${JWT_KEY:4837e9ab8772c5db4e07758a35b14955}
      expiration-time: 12h

spring:
  application:
    name: lifeful

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
