spring:
  application:
    name: readful

  jpa:
    open-in-view: false
    show-sql: true


readful:
  book:
    naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}

    aladin:
      client-id: ${ALADIN_API_CLIENT_ID}
