name: ktlint check

on:
  pull_request:
    branches: [ main ]

jobs:
  ktlint:
    name: Run ktlintCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck
